version: '3'
services:
  postgresql:
    image: postgres:13.2-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
  #  Se ignora por error en cambio de version pero las variables de entorno hacen el mismo trabajo
   #   - init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=user_db
      - POSTGRES_USER=dev1234
      - POSTGRES_PASSWORD=dev1234

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  postgres-data:
    external: false