version: '3'
services:
  postgresql:
    image: postgres:13.2-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
  #  Se ignora por error en cambio de version pero las variables de entorno hacen el mismo trabajo
   #   - init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=user_db
      - POSTGRES_USER=dev1234
      - POSTGRES_PASSWORD=dev1234

  adminer: #GUI web para acceder a la base de datos: localhost:8080
    image: adminer
    restart: always
    depends_on:
      - postgresql
    links:
      - postgresql:5432
    ports:
      - 8080:8080

  spring-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8081:8081
    depends_on:
      - postgresql
    environment:
      - SPRING_R2DBC_URL=r2dbc:pool:postgres://postgresql:5432/user_db
      - SPRING_R2DBC_USERNAME=dev1234
      - SPRING_R2DBC_PASSWORD=dev1234
volumes:
  postgres-data:
    external: false