#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER dev1234 WITH PASSWORD 'dev1234';
    CREATE DATABASE demo;
    GRANT ALL PRIVILEGES ON DATABASE demo TO dev1234;
EOSQL